# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-28 09:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('xcomments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='xcomment',
            options={'ordering': ('submit_date',), 'permissions': [('can_moderate', 'Can moderate comments')], 'verbose_name': 'comment', 'verbose_name_plural': 'comments'},
        ),
        migrations.AddField(
            model_name='xcomment',
            name='comment',
            field=models.TextField(default='', max_length=3000, verbose_name='comment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='xcomment',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True, verbose_name='IP address'),
        ),
        migrations.AddField(
            model_name='xcomment',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Uncheck this box to make the comment effectively disappear from the site.', verbose_name='is public'),
        ),
        migrations.AddField(
            model_name='xcomment',
            name='is_removed',
            field=models.BooleanField(default=False, help_text='Check this box if the comment is inappropriate. A "This comment has been removed" message will be displayed instead.', verbose_name='is removed'),
        ),
        migrations.AddField(
            model_name='xcomment',
            name='submit_date',
            field=models.DateTimeField(db_index=True, default=None, verbose_name='date/time submitted'),
        ),
        migrations.AddField(
            model_name='xcomment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xcomment_comments', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='xcomment',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name="user's email address"),
        ),
        migrations.AddField(
            model_name='xcomment',
            name='user_name',
            field=models.CharField(blank=True, max_length=50, verbose_name="user's name"),
        ),
        migrations.AddField(
            model_name='xcomment',
            name='user_url',
            field=models.URLField(blank=True, verbose_name="user's URL"),
        ),
    ]
