# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-28 13:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xcomments', '0002_change_comments_base_class'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='xcomment',
            options={'permissions': (('can_receive_new_comment_email', 'Can receive notification on new comments'),), 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
    ]
