# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-19 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Desciption')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Date updated')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=128, verbose_name='Name')),
                ('sender_email', models.EmailField(blank=True, max_length=128, verbose_name='Email')),
                ('sender_phone', models.CharField(blank=True, max_length=15, verbose_name='Phone')),
                ('sender_organization', models.CharField(blank=True, max_length=128, verbose_name='Organization')),
                ('message', models.TextField(verbose_name='Message')),
                ('status', models.CharField(blank=True, choices=[('received', 'Received/Read'), ('under review', 'Under review'), ('response sent', 'Response sent')], max_length=128, verbose_name='Status')),
                ('remarks', models.TextField(blank=True, verbose_name='Remarks')),
                ('notified_staff', models.TextField(blank=True, verbose_name='Notified staff')),
                ('category', models.ManyToManyField(blank=True, related_name='feedbacks', to='mrejesho.Category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedback',
            },
        ),
    ]
