# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-19 07:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mrejesho', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 12, 19, 7, 59, 20, 540079, tzinfo=utc), verbose_name='Date created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Date updated'),
        ),
    ]
