# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-19 08:52
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('mrejesho', '0002_add_time _stamp_fields_on_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='sender_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, verbose_name='Phone'),
        ),
    ]
