# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-27 10:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrejesho', '0003_alter_field_sender_phone_to_use_phonenumberfield'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'permissions': (('can_receive_new_feedback_email', 'Can receive notification on new feedback'),), 'verbose_name': 'Feedback', 'verbose_name_plural': 'Feedback'},
        ),
    ]
